export const demoItems = [
  {id:'1', slug:'telepon-putar-klasik', name:'Telepon Putar Klasik', short_description:'Telepon lama dengan dial putar yang menjadi saksi perkembangan komunikasi analog.', description:'Telepon putar klasik ini menunjukkan bagaimana masyarakat dahulu berkomunikasi sebelum hadirnya telepon genggam. Bentuk dial mekanis, gagang berat, dan kabel spiralnya memberi pengalaman visual tentang teknologi komunikasi masa lampau. Koleksi ini cocok untuk menjelaskan perubahan alat komunikasi dari analog menuju digital.', category:'Teknologi & Komunikasi', period:'1970–1990', origin:'Bengkulu', material:'Plastik, logam, kabel', condition:'Terawat', image_url:'/images/collections/collection-1.jpg', views:168},
  {id:'2', slug:'timbangan-jarum-vintage', name:'Timbangan Jarum Vintage', short_description:'Timbangan mekanik dengan jarum penunjuk yang biasa digunakan untuk aktivitas perdagangan.', description:'Timbangan jarum vintage memperlihatkan aktivitas ekonomi masyarakat pada masa lalu. Alat ini digunakan untuk menimbang barang dagangan secara manual. Bentuknya sederhana tetapi memiliki nilai edukasi karena menunjukkan prinsip keseimbangan dan pengukuran tradisional.', category:'Peralatan Dagang', period:'1960–1980', origin:'Bengkulu', material:'Besi, kaca, enamel', condition:'Terawat', image_url:'/images/collections/collection-2.jpg', views:122},
  {id:'3', slug:'neraca-logam-tradisional', name:'Neraca Logam Tradisional', short_description:'Neraca dua sisi sebagai alat ukur berat yang banyak dipakai dalam transaksi lama.', description:'Neraca logam tradisional digunakan untuk membandingkan berat benda dengan anak timbangan. Koleksi ini mengajarkan konsep keseimbangan sekaligus menggambarkan kehidupan pasar lama yang mengandalkan alat ukur manual.', category:'Peralatan Dagang', period:'1950–1970', origin:'Bengkulu', material:'Logam dan kuningan', condition:'Terawat', image_url:'/images/collections/collection-3.jpg', views:139},
  {id:'4', slug:'televisi-tabung-kuno', name:'Televisi Tabung Kuno', short_description:'Televisi tabung sebagai media hiburan dan informasi sebelum era layar datar.', description:'Televisi tabung kuno menjadi simbol perubahan budaya menonton masyarakat. Dengan bentuk besar dan layar cembung, televisi ini pernah menjadi pusat hiburan keluarga. Koleksi ini menjelaskan perkembangan media visual dari perangkat analog menuju digital.', category:'Teknologi & Komunikasi', period:'1980–2000', origin:'Bengkulu', material:'Plastik, kaca, komponen elektronik', condition:'Perlu Perawatan', image_url:'/images/collections/collection-4.jpg', views:214},
  {id:'5', slug:'mesin-ketik-manual', name:'Mesin Ketik Manual', short_description:'Alat tulis mekanik yang digunakan untuk membuat surat dan dokumen resmi.', description:'Mesin ketik manual adalah perangkat penting sebelum komputer digunakan luas. Setiap huruf ditekan secara mekanis dan langsung tercetak di atas kertas. Koleksi ini memperlihatkan budaya administrasi, pendidikan, dan perkantoran masa lampau.', category:'Teknologi & Komunikasi', period:'1960–1980', origin:'Bengkulu', material:'Besi, plastik, tinta pita', condition:'Terawat', image_url:'/images/collections/collection-5.jpg', views:187},
  {id:'6', slug:'gong-tradisional', name:'Gong Tradisional', short_description:'Alat musik pukul berbahan logam yang digunakan dalam kegiatan adat dan pertunjukan.', description:'Gong tradisional memiliki suara khas yang sering digunakan dalam upacara adat, seni pertunjukan, dan kegiatan kebudayaan. Benda ini menggambarkan kekayaan musikal masyarakat Nusantara dan fungsi bunyi dalam kehidupan sosial.', category:'Alat Musik Tradisional', period:'Abad 20', origin:'Bengkulu', material:'Logam', condition:'Terawat', image_url:'/images/collections/collection-6.jpg', views:176},
  {id:'7', slug:'keris-dan-sarung', name:'Keris dan Sarung', short_description:'Senjata tradisional yang memiliki nilai simbolik, seni, dan sejarah.', description:'Keris merupakan benda budaya yang tidak hanya berfungsi sebagai senjata, tetapi juga sebagai simbol kehormatan, identitas, dan nilai spiritual. Bentuk bilah serta sarungnya menunjukkan keahlian kriya logam dan kayu.', category:'Senjata Tradisional', period:'Abad 19–20', origin:'Bengkulu', material:'Besi, kayu, logam hias', condition:'Terawat', image_url:'/images/collections/collection-7.jpg', views:246},
  {id:'8', slug:'miniatur-kapal-tradisional', name:'Miniatur Kapal Tradisional', short_description:'Miniatur kapal yang menggambarkan aktivitas pelayaran dan perdagangan maritim.', description:'Miniatur kapal tradisional menggambarkan hubungan masyarakat Bengkulu dengan laut, pelayaran, dan perdagangan. Koleksi ini dapat digunakan untuk menjelaskan peran transportasi air dalam sejarah daerah pesisir.', category:'Transportasi Tradisional', period:'Modern rekonstruksi', origin:'Bengkulu', material:'Kayu dan tali', condition:'Terawat', image_url:'/images/collections/collection-8.jpg', views:158},
  {id:'9', slug:'patung-tokoh-sejarah', name:'Patung Tokoh Sejarah', short_description:'Patung figur yang merepresentasikan tokoh atau figur penting dalam narasi sejarah.', description:'Patung tokoh sejarah digunakan sebagai media visual untuk mengenalkan tokoh, pakaian, dan simbol tertentu kepada pengunjung. Benda seperti ini membantu museum menyampaikan cerita sejarah secara lebih mudah dipahami.', category:'Artefak Edukasi', period:'Modern', origin:'Bengkulu', material:'Resin atau logam', condition:'Terawat', image_url:'/images/collections/collection-9.jpg', views:109},
  {id:'10', slug:'bust-tokoh-koleksi', name:'Bust Tokoh Koleksi', short_description:'Patung dada tokoh yang digunakan sebagai media pengenalan sejarah.', description:'Bust atau patung dada menampilkan figur tokoh secara visual. Koleksi ini berguna dalam ruang edukasi karena membantu pengunjung mengenal tokoh atau simbol sejarah melalui bentuk tiga dimensi.', category:'Artefak Edukasi', period:'Modern', origin:'Bengkulu', material:'Resin, logam, kaca display', condition:'Terawat', image_url:'/images/collections/collection-10.jpg', views:93},
  {id:'11', slug:'paku-dan-benda-logam-kuno', name:'Benda Logam Kuno', short_description:'Kumpulan benda logam kecil yang memperlihatkan teknik penggunaan material lama.', description:'Kumpulan benda logam ini memperlihatkan ragam peralatan kecil yang digunakan dalam kehidupan sehari-hari. Walaupun bentuknya sederhana, benda seperti ini penting untuk memahami teknologi material dan kebutuhan praktis masyarakat masa lampau.', category:'Peralatan Tradisional', period:'Tidak diketahui', origin:'Bengkulu', material:'Logam', condition:'Terawat', image_url:'/images/collections/collection-11.jpg', views:88},
  {id:'12', slug:'wadah-logam-antik', name:'Wadah Logam Antik', short_description:'Wadah logam lama yang digunakan untuk kebutuhan rumah tangga atau penyimpanan.', description:'Wadah logam antik memperlihatkan peralatan rumah tangga tradisional yang kuat dan fungsional. Benda ini menjadi bagian dari cerita kehidupan sehari-hari masyarakat sebelum hadirnya peralatan modern berbahan plastik atau stainless baru.', category:'Peralatan Rumah Tangga', period:'1950–1980', origin:'Bengkulu', material:'Logam', condition:'Perlu Perawatan', image_url:'/images/collections/collection-12.jpg', views:132}
]

export const demoQuiz = [
  {id:'q1', item_slug:'telepon-putar-klasik', question:'Apa ciri utama telepon putar klasik?', options:['Layar sentuh','Dial putar mekanis','Koneksi bluetooth','Kamera depan'], correct_answer:'Dial putar mekanis'},
  {id:'q2', item_slug:'televisi-tabung-kuno', question:'Televisi tabung termasuk kategori apa?', options:['Alat Musik Tradisional','Teknologi & Komunikasi','Senjata Tradisional','Transportasi Tradisional'], correct_answer:'Teknologi & Komunikasi'},
  {id:'q3', item_slug:'keris-dan-sarung', question:'Keris biasanya termasuk jenis koleksi apa?', options:['Senjata Tradisional','Peralatan Dagang','Alat Musik','Transportasi'], correct_answer:'Senjata Tradisional'},
  {id:'q4', item_slug:'gong-tradisional', question:'Gong tradisional dimainkan dengan cara?', options:['Dipetik','Ditiup','Dipukul','Digesek'], correct_answer:'Dipukul'},
  {id:'q5', item_slug:'mesin-ketik-manual', question:'Mesin ketik manual digunakan untuk membuat?', options:['Dokumen dan surat','Makanan','Alat musik','Kapal'], correct_answer:'Dokumen dan surat'}
]
